project_name: haoke-cli

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: haoke-cli
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - riscv64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - completions/*

release:
  github:
    owner: haokeyingxiao
    name: haoke-cli