name: Smoke Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
          check-latest: true

      - name: Compile haoke-cli
        run: go build

      - name: Checkout Plugin
        uses: actions/checkout@v4
        with:
          repository: 'FriendsOfShopware/FroshTools'
          ref: '75e2013752fd4db7535e4b72b3e3e8d57e531002'
          path: 'plugin'

      - name: Create HaoKe
        run: ./haoke-cli project create shopware 6.5.7.3

      - name: Build asset of Plugin
        run: ./haoke-cli extension zip plugin

      - name: Build asset of Plugin without Git
        run: ./haoke-cli extension zip plugin --disable-git --release

      - name: Validate Plugin
        run: ./haoke-cli extension validate FroshTools.zip

      - name: Get Changelog
        run: ./haoke-cli extension get-changelog FroshTools.zip

      - name: Build asset against custom PROJECT_ROOT
        env:
          HAOKE_PROJECT_ROOT: ${{ github.workspace }}/haoke
        run: |
          mv plugin/.shopware-extension.yml plugin/.shopware-extension-disable.yml
          ./haoke-cli extension build plugin
          mv plugin/.shopware-extension-disable.yml plugin/.shopware-extension.yml

      - name: Install a Storefront Plugin
        working-directory: haoke
        run: |
          composer require 'frosh/platform-filter-search:*' --no-interaction --no-scripts
          rm -rf vendor

      - name: Setup the project
        run: ./haoke-cli project ci haoke