name: Smoke Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
          check-latest: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Compile haoke-cli
        run: go build

      - name: Checkout Plugin
        uses: actions/checkout@v4
        with:
          repository: 'haokeyingxiao-hub/HkagTools'
          ref: 'bc2c28aa7a635aea11fa3b37488711be550a6b84'
          path: 'plugin'

      - name: Create HaoKe
        run: ./haoke-cli project create haoke 6.6.4.7

      - name: Build asset of Plugin
        run: ./haoke-cli extension zip plugin

      - name: Build asset of Plugin without Git
        run: ./haoke-cli extension zip plugin --disable-git --release

      - name: Validate Plugin
        run: ./haoke-cli extension validate FroshTools.zip

      - name: Get Changelog
        run: ./haoke-cli extension get-changelog FroshTools.zip

      - name: Build asset against custom PROJECT_ROOT
        env:
          HAOKE_PROJECT_ROOT: ${{ github.workspace }}/haoke
        run: |
          mv plugin/.haoke-extension.yml plugin/.haoke-extension-disable.yml
          ./haoke-cli extension build plugin
          mv plugin/.haoke-extension-disable.yml plugin/.haoke-extension.yml

      - name: Setup the project
        run: ./haoke-cli project ci haoke